### ISSUE TITLE
Make storage overview sortable

### ISSUE THREAD

**Issue by paulgear** [librenms/librenms#1023]
Need to make sure we can sort by both size and percentage used. @carinity FYI.

**Comment by paulgear** [comment]
Hmmm...  This means we won't be able to include the graphs line any more.  I'm personally not that worried about it, since on any non-trivial LibreNMS instance the page would take too long to load.  But others might find it useful.  I'll keep this change in a feature branch for now.

**Comment by paulgear** [comment]
I wasn't happy with how invasive bootgrid was in terms of its requirements on layout.  I've pushed a version of the health storage screen that is sortable using stupidtable to https://github.com/paulgear/librenms in the health-stupidtable branch as an alternative.  Comments welcome.

**Comment by laf** [comment]
A quick look at stupidtables doesn't seem to show that it supports grabbing data by something like Ajax so aside from enabling support of sorting won't get us away from pages that hit php memory limits and pages that are just to big and browser intense - I could be wrong as I only had a quick look. 

Bootgrid is very flexible even from a css perspective. I'd much prefer we stick with one plugin to work with tables rather than having more js loaded to in essence do the same job.

**Comment by laf** [comment]
Tested the branch and one issue is when sorting by a column with graphs it goes out of synch and shows all the graphs together  rather than inline with a particular storage entry.

**Comment by laf** [comment]
@paulgear The graphs aren't working on this and it's got a few things still wrong but this is with bootgrid with support for graphs.

![image](https://cloud.githubusercontent.com/assets/3941142/7666769/7d4d9a20-fbe8-11e4-8c07-39aee959b412.png)

Give this branch a go if you like:

https://github.com/laf/librenms/tree/issue-1023

**Comment by laf** [comment]
Things that need doing:

Fix device sorting.
Fix usage sorting.
Move device_permitted() to the sql query (see devices table for examples).
Move the two foreach $config['ignore_.... into sql query

I'll leave you to sort those out :)

**Comment by laf** [comment]
All sorted. Check PR #1030

**Comment by paulgear** [comment]
There's something not quite right with the sorting - see attached screenshot.
![screenshot from 2015-05-18 20 28 12](https://cloud.githubusercontent.com/assets/107222/7679049/84aa925e-fd9c-11e4-9a95-b494a903996f.png)

**Comment by f0o** [comment]
Speaking of Storage, did somebody else noticed that the bar of the first entry is always in dark-blue? like regardless of it's %...

**Comment by laf** [comment]
@paulgear fixed in new PR

**Comment by Lonecrowe** [comment]
Any chance this "sort" of sorting can be applied to all results?  There are plenty of times i'd like to sort by CPU usage or temperatures etc.

**Comment by carinity** [comment]
thank you for getting this working for storage !!! great result

**Comment by f0o** [comment]
Closing as it's merged

**Comment by paulgear** [comment]
For the record, colour problem with first object was fixed in commit 2285f8c.
