### ISSUE TITLE
Hide Disabled Ports in /Overview and Device/Ports

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1141]
User story:
I have a network device with 12 ports. Only first 8 ports would be ever used and are connected at the moment. There seems like no way to disable the unused ports completely. If I set them as "Disabled" or/and "Ignored" I can still see them in /Overview
http://fii.cz/qqvbjxjg
Also they are bothering in Device/Ports
http://fii.cz/vumjc
Question how to handle this classification ?
http://fii.cz/djdat

Also for discussion if this should have been handled by the Disabled flag, which is "maybe" used for disable the polling of the iface. Maybe new flag named "Hide" would be more useful. This is up to you.

**Comment by SaaldjorMike** [comment]
Did you shutdown the interfaces on the switches themselves?

**Comment by Ftelf** [comment]
I follow your point. Yes, this is something I figured out few minutes ago. I did that on few routers.
http://fii.cz/dksrhqze
The ports disappeared from the /Overview. I may live with them laying in graphs, they are greyed out.

But there are few devices like wireless bridges with internal loopback, bridges, management devices which cannot be disabled this way. And it's really flustrating to see them around.
http://fii.cz/ztmvymua

**Comment by laf** [comment]
We should fix this anyway so you don't need to disable the ports on your device.

As for internal loopback and things, you can add config options to filter those out: http://docs.librenms.org/Support/Configuration/#interfaces-to-be-ignored

**Comment by laf** [comment]
@Ftelf 

I've just tested this. Setting the port to be ignored for me stops it being shown on the overview page!

Can you send screenshots of the ports you've set to ignore and a screenshot of them appearing on the overview page?

**Comment by Ftelf** [comment]
This is really embarrassing. I did tried this again and the "Ignore" flag did the job. I had to overlook this when tried the combinations of the disabled and ignored. Sorry for wasting your time.

**Comment by Ftelf** [comment]
I can confirm, that "Disabled" ports disappeared from global /Overview list. But they are still present in Device/Overview and also in Device/Ports.
http://fii.cz/rvamv
http://fii.cz/tzaxnwz
http://fii.cz/hrdsvc
http://fii.cz/rtrmpbne

**Comment by YukonRob** [comment]
Sorry to ask this here, new to this format. I can't find anywhere (as per screenshots above) to actually change the disable/ignore/etc settings. I am using a newer build however (8d10089). Nothing comes up in the docs either.

**Comment by laf** [comment]
What do you want to change? I'd probably suggest opening a new issue and reference this issue by doing #1141
