### ISSUE TITLE
ADD: Mellanox Device Support

### ISSUE THREAD

**Issue by ernstae** [librenms/librenms#1328]
I have a few Mellanox devices in my environment, and after having read this document (about obs...) https://community.mellanox.com/docs/DOC-1493, I figured it'd be a no-brainer to have LibreNMS support Mellanox gear:

The devices I have are as follows:

SX1012 12-port 40GbE Switch
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.33049.1.1.1.1012
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1328458757) 153 days, 18:09:47.57
SNMPv2-MIB::sysLocation.0 = STRING: unknown
SNMPv2-MIB::sysContact.0 = STRING: unknown
SNMPv2-MIB::sysName.0 = STRING: sx1012-1
SNMPv2-MIB::sysDescr.0 = STRING: Mellanox SX1012,MLNX-OS,SWvSX_3.4.0012

iso.3.6.1.2.1.1.1.0 = STRING: "Mellanox SX1012,MLNX-OS,SWvSX_3.4.0012"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.33049.1.1.1.1012
iso.3.6.1.2.1.1.3.0 = Timeticks: (1328565400) 153 days, 18:27:34.00
iso.3.6.1.2.1.1.4.0 = STRING: "unknown"
iso.3.6.1.2.1.1.5.0 = STRING: "sx1012-1"
iso.3.6.1.2.1.1.6.0 = STRING: "unknown"
iso.3.6.1.2.1.1.7.0 = INTEGER: 72
iso.3.6.1.2.1.1.8.0 = Timeticks: (58) 0:00:00.58

----------
SX1036 36-port 40GbE switch
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.33049.1.1.1.1036
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (478998480) 55 days, 10:33:04.80
SNMPv2-MIB::sysLocation.0 = STRING: unknown
SNMPv2-MIB::sysContact.0 = STRING: unknown
SNMPv2-MIB::sysName.0 = STRING: sx1036-1
SNMPv2-MIB::sysDescr.0 = STRING: Mellanox SX1036,MLNX-OS,SWv3.4.1100

iso.3.6.1.2.1.1.1.0 = STRING: "Mellanox SX1036,MLNX-OS,SWv3.4.1100"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.33049.1.1.1.1036
iso.3.6.1.2.1.1.3.0 = Timeticks: (479070166) 55 days, 10:45:01.66
iso.3.6.1.2.1.1.4.0 = STRING: "unknown"
iso.3.6.1.2.1.1.5.0 = STRING: "sx1036-1"
iso.3.6.1.2.1.1.6.0 = STRING: "unknown"
iso.3.6.1.2.1.1.7.0 = INTEGER: 72
iso.3.6.1.2.1.1.8.0 = Timeticks: (64) 0:00:00.64

------

Mellanox I5300 36-port Infiniband Switch
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.33049.2.1
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1358817690) 157 days, 6:29:36.90
SNMPv2-MIB::sysLocation.0 = STRING: Seattle, USA
SNMPv2-MIB::sysContact.0 = STRING: unknown
SNMPv2-MIB::sysName.0 = STRING: switch-63014c
SNMPv2-MIB::sysDescr.0 = STRING: Linux switch-63014c 2.6.27-MELLANOXuni-m405ex EFM_PPC_M405EX EFM_1.1.3000 #1 2013-07-08 14:29:44 ppc

iso.3.6.1.2.1.1.1.0 = STRING: "Linux switch-63014c 2.6.27-MELLANOXuni-m405ex EFM_PPC_M405EX EFM_1.1.3000 #1 2013-07-08 14:29:44 ppc"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.33049.2.1
iso.3.6.1.2.1.1.3.0 = Timeticks: (1358894078) 157 days, 6:42:20.78
iso.3.6.1.2.1.1.4.0 = STRING: "unknown"
iso.3.6.1.2.1.1.5.0 = STRING: "switch-63014c"
iso.3.6.1.2.1.1.6.0 = STRING: "Seattle, USA"
iso.3.6.1.2.1.1.7.0 = INTEGER: 0
iso.3.6.1.2.1.1.8.0 = Timeticks: (336) 0:00:03.36

I'm happy to help on testing this, but don't have much bandwidth right now for coding up a solution.

**Comment by laf** [comment]
I've done the basic code to hopefully get detection in. To test do this:

```bash
cd /opt/librenms
git remote add laf https://github.com/laf/librenms.git
git remote update laf
git checkout issue-1328
./discovery.php -h HOSTNAME -d -m system
./poller.php -h HOSTNAME -d -r -m system,os
```

If it doesn't do what you expect, send the output from the discovery and poller commands to us via pastebin or something (edit any sensitive info).

When you are happy it works, I'd suggest going back to master and wait until we merge these changes in:

```bash
git checkout master
```

**Comment by infernix** [comment]
Couple of things:

- IB ports on a IS50xx aren't being detected at all and so aren't being graphed
- SX17xx series is misdetected as Cisco NX-OS, probably because of "Mellanox MSX1710,MLNX-OS,SWv3.4.1120" in sysDescr
- IB ports on the SX17xx series are being detected as "/sx/$portnum", should probably be ib/$portnm for better clarity
- Seems to be getting classified incorrectly as Server

Poller and discover data is here http://pastebin.ca/3039529

**Comment by laf** [comment]
@infernix 

If you do a git remote update laf then git pull to update. The only thing I've fixed is the NX-OS detection.

If you re-run the discovery command again and see if the SX17 is picked up as Mellanox now that would be good.

For other two I need ./discovery.php -h HOSTNAME -d -m ports and ./poller.php -h HOSTNAME -d -r -m ports

For the server being classified - can you confirm which device please?

**Comment by infernix** [comment]
The IS5030 (infiniband only) ports are not being found at all by default.. discovery and poller data here: http://pastebin.ca/3040779

When I add this MIB http://www.mellanox.com/related-docs/prod_ib_switch_systems/MELLANOX-MIB.zip I am able to retrieve the IB port data like this:

    snmpwalk -v2c -c public myis5030.somecompany.com -m +MELLANOX-MIB . | grep MELLANOX-MIB

Output from that is here: http://pastebin.ca/3040790


As for the SX17xx series, the server classification applied to those but that is now fixed with https://github.com/librenms/librenms/commit/57159cc8cd19500a557568595f76cedb61dc7daa it seems. discover and poller output is here: http://pastebin.ca/3040794

It seems that those /SX/ port names are returned though snmp so that seems valid, just weirdly named. But other than that these now seem fine.

**Comment by ernstae** [comment]
@laf - The changes look brilliant, and work well for the Ethernet devices I am running (SX1012, SX1036), and all the inventory details with the cable types looks great, too!

Our SI5030 Infiniband switch only shows the 'lo' interface, and can second @infernix's experience.

My discovery/polling is available:  http://pastebin.com/U0mfjBgd

**Comment by ernstae** [comment]
The output from the
```./discovery.php -h ib-switch.censored.some.company -d -m ports```
is available here:  http://pastebin.com/pvAmxa0Z

and the output from
```./poller.php -h ib-switch.censored.some.company -d -r -m ports```
is available here:  http://pastebin.com/2pY0PiuK

**Comment by azhermughal** [comment]
I have Mellanox SX6036 available and can help in running any command to it.

**Comment by ernstae** [comment]
Greetings,

I recently added an SX6710 switch to my environment (36-port FDR IB), and LibreNMS works perfectly with it.

I still have issues with the IB ports on a IS50xx not being detected at all and so aren't being graphed, which is the same isssue reported by @infernix and my comment from June 30 above is still relevant.

**Comment by khobbits** [comment]
I've got a mx-sx1400 and it appears to be working fine on the surface, but looking at the graphs, show something completely different.

This is the graphs from a link between the mellanox and another device
Mellanox:
http://i.imgur.com/ZRmC7of.png
Other device:
http://i.imgur.com/2Rre9n1.png

The Mellanox poller seems to be fine:
http://i.imgur.com/NlsKXDH.png

**Comment by khobbits** [comment]
Any idea on what this could be?  Since I'm seeing these weird spikes, i've had to disable alerts on this device, as the traffic is spiking past the speed of the interface.

**Comment by laf** [comment]
I have a PR in the queue that should fix this but it's not been merged yet.

**Comment by khobbits** [comment]
@laf that pr wouldn't address the fact I see zero traffic on the link between spikes would it? (Maybe I found the wrong one).
Compare the two interface screenshots to see what I mean.  Those are different sides of the same cable.

**Comment by khobbits** [comment]
Just in case this helps to pin down the issue: http://i.imgur.com/PBA7gYZ.png, this is on current master branch.

**Comment by wisehippy** [comment]
@laf sorry for a late reply on this thread.  I'm having problems getting any port + port graphing data to work with a Mellanox SX-1036, but it was reported by @ernstae that your branch 'issue-1328' did work perfectly with the SX-1036.  Wish I had that luck...

I can use 'snmpwalk' and pull down port data no problem and also confirm MIB data is being pulled back with 'poller.php' as well on LibreNMS side.

The bummer part is I don't see 'issue-1328' or 'issue-1357' anywhere in remote branches to pull?  Are these changes already integrated in?

Let me know.

**Comment by laf** [comment]
issue-1328 was merged in

We will need the output of:

```bash
./discovery.php -h HOSTNAME -d -m ports
./poller.php -h HOSTNAME -d -r -f -m ports
```

**Comment by wisehippy** [comment]
@laf - Good to know it was merged.  I 'assumed' but thanks for confirming.  

Problem solved on my end.  I actually got the ports to come up no problem, but on initial add of the Mellanox device, I did finally notice that 'device > tab=edit > section=modules > module=ports' was disabled by default.

I was getting perfect data back with '-m ports' argument on discovery and poller scripts but just wasn't on the UI.

Is there any logic driving default-enabled pre-set modules for device types?  That would be my only question --- certainly didn't do that with any of my Cisco/Extreme switches.

**Comment by laf** [comment]
No logic, if you have it globally disabled it will still show as enabled for that device but globally disabled - if it's showing as locally disabled - someone's clicked the button :)

**Comment by murrant** [comment]
Probably the default$config['badif'] we ship..

**Comment by laf** [comment]
No further info provided.
