### ISSUE TITLE
Error in OSPF module

### ISSUE THREAD

**Issue by Negatifff** [librenms/librenms#13537]
### The problem

I have several hundred generic devices, which, in fact, are monitored only for availability and system information, without graphs.
Also I have several thousand devices that are monitored with graphs. 
And the poller OSPF module is globally included. 
Everything worked great, but starting from November 13, 2021, these few hundred generic devices began to constantly hang in the list of unpolled devices. When I started to deal with this, I found that when I started it manually with the OSPF module turned on, an error occurred:

"Too few arguments to function LibreNMS\Modules\Ospf::LibreNMS\Modules\{closure}(), 2 passed and exactly 3 expected"

If the OSPF module is disabled for this device, there is no error. 

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-17-gc05a7a5
DB Schema | 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (228)
PHP       | 7.3.28
Python    | 3.6.8
MySQL     | 10.5.9-MariaDB
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[INFO]  Detected Python Wrapper
[OK]    Connection to memcached is ok
```

### Anything in the logs that might be useful for us?

```txt
#### Load poller module ospf ####
 Processes: .1 Areas: .1 Ports:
In Ospf.php line 115:

  Too few arguments to function LibreNMS\Modules\Ospf::LibreNMS\Modules\{closure}(), 2 passed and exactly 3 expected
```

**Comment by murrant** [comment]
@Negatifff we already merged a fix for this.  According to your version, you are on the sha right before it.
#13530

**Comment by murrant** [comment]
I also have a further fix later that will catch all errors, not just exceptions so polling can continue even after an error.

**Comment by Negatifff** [comment]
Indeed, I did not notice the already existing PR (I was looking only in open ones). thanks, after the update, the problem is almost completely gone. but not for all devices. in particular for os=deltups, the problem remains. I hope you know about it :)

**Comment by murrant** [comment]
@Negatifff no, can you please provide the output from an snmpwalk of OSPF-MIB::ospfIfTable from that device?

**Comment by wqr** [comment]
Some weird devices return this:
```
snmpwalk -c public -v2c 10.10.123.240 OSPF-MIB::ospfIfTable
SNMPv2-MIB::sysDescr.0 = STRING: IP1826
Error: OID not increasing: OSPF-MIB::ospfIfTable
 >= SNMPv2-MIB::sysDescr.0

```

**Comment by Negatifff** [comment]
> @Negatifff no, can you please provide the output from an snmpwalk of OSPF-MIB::ospfIfTable from that device?

snmpwalk -v1 -c public 172.20.92.14 1.3.6.1.2.1.14.7
SNMPv2-SMI::mib-2.14.7 = NULL

**Comment by murrant** [comment]
@Negatifff fancy

**Comment by Negatifff** [comment]
> @Negatifff fancy

what you mean? I can show full snmp tree for that ups

**Comment by murrant** [comment]
I mean, why the hell does it return "NULL" for a non-existent OID, or at least one that should be non-existent.  That is not standard SNMP behavior.

**Comment by Negatifff** [comment]
yes, the behavior is non-standard. but the device is rather flawed. but what is.

**Comment by murrant** [comment]
That is what I meant by fancy.  I'll think on how to handle this invalid input best.

**Comment by murrant** [comment]
@wqr can you figure out if the `Error: OID not increasing` is in stdout or stderr?  Add ` 2>stderr.txt` to the snmpwalk command and check the contents of the file and what is displayed on the screen.

**Comment by wqr** [comment]
First line stdout:
```
SNMPv2-MIB::sysDescr.0 = STRING: IP1826
```
other lines stderr (including an empty line at the end):
```
Error: OID not increasing: OSPF-MIB::ospfIfTable
 >= SNMPv2-MIB::sysDescr.0

```
Actually it does the same things for any not supported OID
```
snmpwalk -On -c public -v2c 10.10.123.240 .1.3.6.1.2.100.2.2.1.1
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
Error: OID not increasing: .1.3.6.1.2.100.2.2.1.1
 >= .1.3.6.1.2.1.2.2.1.1.1

```
```
snmpwalk -On -c public -v2c 10.10.123.240 .1.3.6.1.2.200.2.2.1.1
.1.3.6.1.2.1.1.1.0 = STRING: IP1826
Error: OID not increasing: .1.3.6.1.2.200.2.2.1.1
 >= .1.3.6.1.2.1.1.1.0

```

**Comment by murrant** [comment]
@wqr oh, I forgot one more thing. After running the snmpwalk, check the exit code `echo $?`  (Thanks a ton)

**Comment by wqr** [comment]
The exit code is `1`
