### ISSUE TITLE
ifSpeed Custom Changes Revert Back On Next Poll

### ISSUE THREAD

**Issue by BirdDawg01** [librenms/librenms#15226]
### The problem

Custom ifSpeed changes do not save and revert back to the default after the next poll. 
This randomly started on 8-13-2023 for all devices in NMS, after running fine for close to 2 years. 
Luckily there were only a few custom ifSpeed assigned. 
![image](https://github.com/librenms/librenms/assets/109314993/f87494e7-e8d3-4fac-bc09-b6178f65cb4f)
![image](https://github.com/librenms/librenms/assets/109314993/39d96b0e-91e6-4bc0-90dc-881190df4858)
Reverted back after next poll:
![image](https://github.com/librenms/librenms/assets/109314993/535205fe-92d6-4352-9037-aa723eeb992f)
Recent event showing it was manually set to 40Gbps and changed back:
![image](https://github.com/librenms/librenms/assets/109314993/3a720aaf-7898-4f44-9f42-64240e534eda)

The only way to fix is updating the interface bandwidth on the device which then causes graphs to not fill out correctly. 
![image](https://github.com/librenms/librenms/assets/109314993/eb694d8f-ec4a-43ac-b6c5-ffbe14c6b955)

### Output of ./validate.php

```txt
librenms@librenms-01:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.7.0-75-g8ee1a2034 (2023-08-14T08:16:45-05:00)
DB Schema | 2023_08_02_120455_vendor_ouis_unique_index (255)
PHP       | 8.1.11
Python    | 3.9.2
Database  | MariaDB 10.5.15-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[FAIL]  We have detected that your database schema may be wrong
Database: extra table (report_high_optical_errors_7_days)
Database: extra table (report_low_optical_power_near_end_7_days)
Database: extra table (report_ont_went_missing)
Database: extra table (report_sdber_errors_7_days)
        [FIX]:
        Run the following SQL statements to fix it
        SQL Statements:
         DROP TABLE `report_high_optical_errors_7_days`;
         DROP TABLE `report_low_optical_power_near_end_7_days`;
         DROP TABLE `report_ont_went_missing`;
         DROP TABLE `report_sdber_errors_7_days`;
Attempt to fix this issue (y or n)?:n
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         scripts/syslog-notify-oxidized.php
[FAIL]  We have found some files that are owned by a different user than 'librenms', this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX]:
        sudo chown -R librenms:librenms /opt/librenms
        sudo setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        sudo chmod -R ug=rwX /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        Files:
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/Google.rrd
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/Level_3.rrd
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/Cloudflare.rrd
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/server/Old files
         /opt/librenms/rrd/smokeping/server/<OMMITTED>
          and 45 more...
```

**Comment by fjbf** [comment]
I get the same behavior from the same day

**Comment by JvGinkel** [comment]
Same issue here, for now I disabled alerting on the irb devices but would love to see a fix for this.

**Comment by JvGinkel** [comment]
I'm sorry to say but the issue is not resolved.

All ifSpeed are now set to 1 so I have all the alerts going off right now. And when I update a value it will be set back to 1 after a snmp update.

![Screenshot 2023-08-21 at 08 46 56](https://github.com/librenms/librenms/assets/7691054/f288a335-49b9-499a-b4e0-7a21f17ff10d)

**Comment by murrant** [comment]
They will all be 1bps until you re-set them due to the nature of the bug.  See #15238

**Comment by JvGinkel** [comment]
What I did was do a select on the database for all entries that had the value of 1 with:

`select * from devices_attribs where attrib_type like '%ifspeed%' and attrib_value = '1';` and then deleted these. Then after some time (re-discover/polling/snmp triggered by cron) I fixed those that need a fix and that was it for me.

**Comment by BloodyIron** [comment]
I'm still having this issue for VMs I migrate between hosts and other such things:

```
Version | 23.8.2-25-g6d1b1ac1f - Sun Sep 03 2023 21:47:23 GMT-0600
-- | --
Database Schema | 2023_09_01_084057_application_new_defaults (258)

Version	[23.8.2-25-g6d1b1ac1f - Sun Sep 03 2023 21:47:23 GMT-0600](https://www.librenms.org/changelog.html)
Database Schema	2023_09_01_084057_application_new_defaults (258)
```

Can we please get this issue re-opened? This is NOT resolved. I will keep getting false positives over time until this is fixed.

**Comment by murrant** [comment]
@BloodyIron you need to manually update them.  Alternatively, LibreNMS could delete all overrides, but most users don't know what they had overriden.  The command posted in #15238 or raw sql https://github.com/librenms/librenms/issues/15226#issuecomment-1693072236 allow you to find the ones that need to be updated.

The problem is the stupid way the override was being stored (only in ifSpeed), once the bug occurred, the override value was permanently lost.

**Comment by BloodyIron** [comment]
So I ran the command as librenms user to show the ports with attrib_value = 1. However the device_id's it refers to are hypervisors, and the ports that are being shown "don't exist currently" so to say, as the port they correspond to is a VM that is not currently on that hypervisor node/host (but the VM(s) have been on that node/host in the past).

Is there any way (without going into SQL) to update/delete the attrib_value for these ports through the webGUI? Since the VMs are not on said hosts/nodes currently, I do not see them in the port list for the listed hosts/nodes each refers to. (I hope that's clear?)

**Comment by murrant** [comment]
@BloodyIron to remove all incorrect overrides (set to 1), run this command (it will not output anything):
```
lnms tinker --execute="DeviceAttrib::where('attrib_type', 'like', 'ifSpeed:%')->where('attrib_value', '1')->delete()"
```

**Comment by murrant** [comment]
Otherwise, if you want to do things in the gui, you would have to go to each device > settings > ports > and look for port speeds set to 1 and delete them to revert to detected speed or set them to the desired override value.

**Comment by BloodyIron** [comment]
> Otherwise, if you want to do things in the gui, you would have to go to each device > settings > ports > and look for port speeds set to 1 and delete them to revert to detected speed or set them to the desired override value.

The ports don't show up in the GUI as the VMs are not on those hosts. So the CLI command you've presented may be my best option. Thanks though! Also, thanks for your continued work on libreNMS! :D
