### ISSUE TITLE
junos IPv6 peers polling issue

### ISSUE THREAD

**Issue by rAGSebastianRost** [librenms/librenms#16860]
### The problem

In librenms.log, i see this error:

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'bgpPeerState' cannot be null (Connection: mysql, SQL: UPDATE `bgpPeers` set `bgpPeerState`=?,`bgpPeerAdminStatus`=?,`bgpPeerInUpdates`=0,`bgpPeerOutUpdates`=0,`bgpPeerInTotalMessages`=0,`bgpPeerOutTotalMessages`=0,`bgpPeerFsmEstablishedTime`=0,`bgpLocalAddr`= WHERE `device_id` = 366 AND `bgpPeerIdentifier` = 2001:ad8::5) (Connection: dbFacile, SQL: UPDATE `bgpPeers` set `bgpPeerState`=?,`bgpPeerAdminStatus`=?,`bgpPeerInUpdates`=0,`bgpPeerOutUpdates`=0,`bgpPeerInTotalMessages`=0,`bgpPeerOutTotalMessages`=0,`bgpPeerFsmEstablishedTime`=0,`bgpLocalAddr`= WHERE `device_id` = 366 AND `bgpPeerIdentifier` = 2001:ad8::5)#0 /opt/librenms/includes/polling/bgp-peers.inc.php(532): dbUpdate()
#1 /opt/librenms/LibreNMS/Modules/LegacyModule.php(115): include('...')
#2 /opt/librenms/app/Jobs/PollDevice.php(139): LibreNMS\Modules\LegacyModule->poll()
#3 /opt/librenms/app/Jobs/PollDevice.php(63): App\Jobs\PollDevice->pollModules()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\PollDevice->handle()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(254): Illuminate\Queue\SyncQueue->push()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(230): Illuminate\Bus\Dispatcher->pushCommandToQueue()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(95): Illuminate\Bus\Dispatcher->dispatchToQueue()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(76): Illuminate\Bus\Dispatcher->dispatchSync()
#24 /opt/librenms/app/Console/Commands/DevicePoll.php(79): App\Jobs\PollDevice::dispatchSync()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#31 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#32 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#33 /opt/librenms/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#34 /opt/librenms/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#35 /opt/librenms/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#36 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#37 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#38 /opt/librenms/lnms(38): App\Console\Kernel->handle()
#39 {main}`

### Output of ./validate.php

```txt
librenms@librenms-prod:~$ ./validate.php
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-84-gac7c8e747 (2024-12-08T16:21:08+01:00)
DB Schema | 2024_10_24_131715_mpls_sdp_bindings_enum_string (310)
PHP       | 8.2.26
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[FAIL]  We have detected that your database schema may be wrong
Database: incorrect column (cef_switching/punt)
Database: incorrect column (cef_switching/punt_prev)
        [FIX]:
        Run the following SQL statements to fix it
        SQL Statements:
         ALTER TABLE `cef_switching` CHANGE `punt` `punt` int NOT NULL ;
         ALTER TABLE `cef_switching` CHANGE `punt_prev` `punt_prev` int NOT NULL ;
Attempt to fix this issue (y or n)?:n
[OK]    MySQL and PHP time match
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

21.11.0

### Anything in the logs that might be useful for us?

```txt
see above
```

**Comment by robje** [comment]
I've added a few debug statements to `includes/polling/bgp-peers.inc.php`

```diff
diff --git a/includes/polling/bgp-peers.inc.php b/includes/polling/bgp-peers.inc.php
index 6e198ba74..05d435bc5 100644
--- a/includes/polling/bgp-peers.inc.php
+++ b/includes/polling/bgp-peers.inc.php
@@ -114,6 +114,8 @@ if (! empty($peers)) {
                         // parse peer IP
                         $junos = [];
                         foreach ($peer_data_check as $peers => $jnx_peer_data) {
+                            echo "peer : {$peers} - jnx_peer_data : \n";
+                            var_dump($jnx_peer_data);
                             $exploded_ip = explode('.', $peers);
                             $ip_offset = count($exploded_ip) > 30 ? -16 : -4;
                             $tmp_peer_ip = Oid::of(implode('.', array_slice($exploded_ip, $ip_offset)))->toIp()->uncompressed();
@@ -122,6 +124,7 @@ if (! empty($peers)) {
                     }
 
                     $address = $peer_ip->uncompressed();
+                    echo "address : {$address} - toSnmpIndex : {$peer_ip->toSnmpIndex()}\n";
                     $peer_data = [
                         'bgpPeerState' => $junos[$address]['BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerState'] ?? null,
                         'bgpPeerAdminStatus' => $junos[$address]['BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerStatus'] ?? null,
```

It looks like retrieved BGP peerdata for ipv4 is an ipv4 address in dotted quad notation. For ipv6 peers it is reprecented as some weird string.

```text
peer : 0.ipv4..213.198.77.138.1.213.198.77.137 - jnx_peer_data : 
peer : 0.ipv6."..(..P........r. ..(..P........q" - jnx_peer_data : 
```

To me it looks like `$address` in `$junos[$address]` does not match anything for an ipv6 peer. This causes the `$peer_data` structure to be filled with NULL including column 'bgpPeerState'. This in turn causes the mysql error.

I don't see a way to fix this.

Attached is the full output of `lnms device:poll -m bgp jun1.fra4.oob.dmz.bit.nl -vvv`

[juniper_bgp_poller_run.log](https://github.com/user-attachments/files/18240544/juniper_bgp_poller_run.log)

**Comment by murrant** [comment]
That is weird, the IPv6 was represented correctly on my computer.

**Comment by robje** [comment]
> That is weird, the IPv6 was represented correctly on my computer.

Dunno what the differences would be. We run LibreNMS on Ubuntu 24.04.1 LTS (upgraded from 20.04) and Junos 21.2R3

**Comment by robje** [comment]
Worked around the the logspam by changing the following:

```diff
-                        'bgpPeerState' => $junos[$address]['BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerState'] ?? null,
-                        'bgpPeerAdminStatus' => $junos[$address]['BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerStatus'] ?? null,
+                        'bgpPeerState' => $junos[$address]['BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerState'] ?? 'unknown',
+                        'bgpPeerAdminStatus' => $junos[$address]['BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerStatus'] ?? 'unknow',
```

**Comment by domleb** [comment]
We getting this error as well and it's spamming the logs

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'bgpPeerState' cannot be null (Connection: mysql, SQL: UPDATE `bgpPeers` set `bgpPeerState`=?,`bgpPeerAdminStatus`=?,`bgpPeerInUpdates`=0,`bgpPeerOutUpdates`=0,`bgpPeerInTotalMessages`=0,`bgpPeerOutTotalMessages`=0,`bgpPeerFsmEstablishedTime`=0,`bgpLocalAddr`= WHERE `device_id` = 14 AND `bgpPeerIdentifier` = 2001:7f8:4:1::1525:1) (Connection: dbFacile, SQL: UPDATE `bgpPeers` set `bgpPeerState`=?,`bgpPeerAdminStatus`=?,`bgpPeerInUpdates`=0,`bgpPeerOutUpdates`=0,`bgpPeerInTotalMessages`=0,`bgpPeerOutTotalMessages`=0,`bgpPeerFsmEstablishedTime`=0,`bgpLocalAddr`= WHERE `device_id` = 14 AND `bgpPeerIdentifier` = 2001:7f8:4:1::1525:1)#0 /opt/librenms/includes/polling/bgp-peers.inc.php(532): dbUpdate()
#1 /opt/librenms/LibreNMS/Modules/LegacyModule.php(115): include('...')
#2 /opt/librenms/app/Jobs/PollDevice.php(139): LibreNMS\Modules\LegacyModule->poll()
#3 /opt/librenms/app/Jobs/PollDevice.php(63): App\Jobs\PollDevice->pollModules()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\PollDevice->handle()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(254): Illuminate\Queue\SyncQueue->push()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(230): Illuminate\Bus\Dispatcher->pushCommandToQueue()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(95): Illuminate\Bus\Dispatcher->dispatchToQueue()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(76): Illuminate\Bus\Dispatcher->dispatchSync()
#24 /opt/librenms/app/Console/Commands/DevicePoll.php(79): App\Jobs\PollDevice::dispatchSync()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#31 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#32 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#33 /opt/librenms/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#34 /opt/librenms/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#35 /opt/librenms/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#36 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#37 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#38 /opt/librenms/lnms(38): App\Console\Kernel->handle()
#39 {main} 
```

**Comment by domleb** [comment]
I've reverted to release `24.11.0` and I'm no longer getting the error.

**Comment by murrant** [comment]
We are running 23.4R2, perhaps it is fixed in that release?
Assuming it is a JunOS bug, I think your work-around would be acceptable.

**Comment by peejaychilds** [comment]
We are seeing the same issues after 24.12 update
The specific instance I am investigating is a MX960 running 22.2R3-S1.9

**Comment by peejaychilds** [comment]
I _think_ this will show up for any IPv6 peering in 2000::/3 (begins with 0x20 in the first octet)

The session needs to be established to see the issue

I can't find a wiggle flag in net-snmp to disable this behaviour ... I assume somewhere an 'isspace()' function is causing the issue or perhaps isprint/isascii (?).    It might also occur with IPv4 perhaps if the peer is in the 32.x.x.x range (not validated)

Perhaps adding the '-b' flag would produce a more consistent output ?

```
snmpbulkwalk -M /opt/librenms/mibs:/opt/librenms/mibs/junos -m SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB -v2c -c REDACTED -OQXUt -Pu udp:dut:161 BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerIndex | grep 42$
BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerIndex[0][ipv6][". 5...G......... . 5...G........"] = 42

snmpbulkwalk -M /opt/librenms/mibs:/opt/librenms/mibs/junos -m SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB -v2c -c REDACTED -OQXUtb -Pu udp:dut:161 BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerIndex | grep 42$
BGP4-V2-MIB-JUNIPER::jnxBgpM2PeerIndex.0.2.32.1.32.53.0.0.8.71.0.0.0.0.0.0.0.2.2.32.1.32.53.0.0.8.71.0.0.0.0.0.0.0.1 = 42

```

I also think if the session isn't established the index doesn't contain the neighbour address yet so it doesn't trigger this issue ...   so it appears the juniper 'index' changes when the state changes

I assume the other way 'around' it might be to not assume the neighbour and local addresses are in the index and treat the index as a hash and get the neighbour address from jnxBgpM2PeerRemoteAddr etc

**Comment by wdoekes** [comment]
After applying https://github.com/librenms/librenms/pull/16988 on 24.12.0, I still get these for IPv4 addresses, but there are now a lot fewer than before:
```
2025-01-16 10:32:38.183841+0100: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'bgpPeerState' cannot be null (Connection: mysql, SQL: UPDATE `bgpPeers` set `bgpPeerState`=?,`bgpPeerAdminStatus`=?,`bgpPeerFsmEstablishedTime`=17619144,`bgpLocalAddr`=1.1.1.1 WHERE `device_id` = 57 AND `bgpPeerIdentifier` = 1.1.1.1) (Connection: dbFacile, SQL: UPDATE `bgpPeers` set `bgpPeerState`=?,`bgpPeerAdminStatus`=?,`bgpPeerFsmEstablishedTime`=17619144,`bgpLocalAddr`=1.1.1.1 WHERE `device_id` = 57 AND `bgpPeerIdentifier` = 1.1.1.1)#0 /srv/librenms/includes/polling/bgp-peers.inc.php(537): dbUpdate()
```
```
mysql> select device_id, last_polled, hardware from devices where device_id in (57);
+-----------+---------------------+------------------------------------+
| device_id | last_polled         | hardware                           |
+-----------+---------------------+------------------------------------+
|        57 | 2025-01-16 09:34:09 | Juniper JNP204 [MX204] Edge Router |
+-----------+---------------------+------------------------------------+
1 row in set (0.00 sec)
```
Do you have tips to debug this further?
