### ISSUE TITLE
API-tokens with LDAP authentication

### ISSUE THREAD

**Issue by Ultra2D** [librenms/librenms#3069]
The API part of the WebUI does not work with LDAP authentication at the moment. I have fixed it for myself for now, as this probably will be changed as part of the rewrite (#2965).

The id of the user creating a token is saved in the database. To display the tokens, function `get_user($user_id)` is used. Will that stay the same after the rewrite? 
I ask, because that function is not supported by LDAP authentication at the moment, but can be added quite easily.

**Comment by awlx** [comment]
Same for Active Directory support :(.

**Comment by TJuberg** [comment]
@Ultra2D Would you mind sharing your fix for the interim?

**Comment by laf** [comment]
@TJuberg just insert a token straight into the tokens table in the DB.

**Comment by TJuberg** [comment]
Thank you.

Just getting started with LibreNMS and don't know my way around yet :)

**Comment by laf** [comment]
No worries, that's a bodge at the moment :(

**Comment by Ultra2D** [comment]
@laf  get_user() is missing from LDAP auth. Should it be added?

**Comment by compuguy** [comment]
I think this hasn't been fixed even with merge #3178.

**Comment by Ultra2D** [comment]
Correct, this is caused by looking for users in the database, which does not work for LDAP users  ( https://github.com/librenms/librenms/blob/5600bf3995024b11bb49e2294d2b4d4bc37b9dde/html/pages/api-access.inc.php#L57 ). But I think this should be fixed during/after the rewrite (also see https://github.com/librenms/librenms/issues/3128#issuecomment-194494246 ).

**Comment by f0rkz** [comment]
Is there any update to this issue?

**Comment by networkpadawan** [comment]
any update or workaround?

**Comment by Ultra2D** [comment]
This issue is closed, so you might have to create a new one if it does not work for you. For me, creating an access token using the web interface does work at the moment. Otherwise you can always add an entry to table 'api_tokens' manually .

**Comment by dneto82** [comment]
HI. I created the token manually in database, but still getting.

"message": "API Token is missing or invalid; please supply a valid token"

**Comment by murrant** [comment]
Does LDAP support using a bind user?  Otherwise, it cannot perform ldap actions that require authentication in the api.

**Comment by zlesnr** [comment]
@laf I don't believe this to be fixed.  Would you mind reopening this please?  We've just brought up LibreNMS in our environment and we'd like to use the API, but strictly use LDAP for authentication.
