### ISSUE TITLE
Fortigate eventlog messages about speed changes

### ISSUE THREAD

**Issue by basn** [librenms/librenms#4090]
I keep getting messages in the eventlog about 	"ifHighSpeed: 4000 -> 0" or "ifSpeed: 4000000000 -> 0" etc, i am running latest and everything else works as intended.

as instructed here is the following information i have changed hostname etc due to privacy concerns but if there is anything please contact me.

[fortigate.txt](https://github.com/librenms/librenms/files/422012/fortigate.txt)

====================================
Version info:
Commit SHA: d7d4c4a067db9b1ebf4b69d1c01df207bd2d99f0
DB Schema: 127
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3

====================================

**Comment by Rosiak** [comment]
Should be fixed in #4099 closing.

**Comment by basn** [comment]
Is this updated in the code now? so its supposed to be fixed when running daily update?

**Comment by Rosiak** [comment]
@basn Yes, this is now in the master.

**Comment by basn** [comment]
Hm, i still have the issue after doing the daily update.
I redid the update after seeing this.

**Comment by basn** [comment]
Nope still the same sorry to say

**Comment by laf** [comment]
You will need to run a few of the poller ports debugs to capture both sides of the events here I'm afraid :(

**Comment by laf** [comment]
Any further info?

**Comment by basn** [comment]
I think its the device, i have looked at the other fortigates... and i have 2 with special setups with so many vlans so its that that causes it..
