### ISSUE TITLE
duplicated snmp updates spamming eventlog

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [librenms/librenms#5448]
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | bfe6ce610c58ab301b17451d18abc945564162c5
DB Schema | 154
PHP       | 7.0.13-0ubuntu0.16.04.1
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

eventlog filled with `IF-MIB OID: 0 -> value` 

>2017-01-15 22:39:01	localhost	NULL	Could not issue critical alert for rule 'Sensor under limit' to transport 'mail' Error: You must provide at least one recipient email address.
2017-01-15 22:35:10	debian86_vm	eth0	ifDuplex: 0 -> fullDuplex
2017-01-15 22:35:10	debian86_vm	eth0	ifConnectorPresent: 0 -> true
2017-01-15 22:35:10	debian86_vm	eth0	ifPromiscuousMode: 0 -> false
2017-01-15 22:35:10	debian86_vm	eth0	ifPhysAddress: 0 -> 005056bf4050
2017-01-15 22:35:10	debian86_vm	eth0	ifType: 0 -> ethernetCsmacd
2017-01-15 22:35:10	debian86_vm	eth0	ifOperStatus: 0 -> up
2017-01-15 22:35:10	debian86_vm	eth0	ifAdminStatus: 0 -> up
2017-01-15 22:35:10	debian86_vm	eth0	ifAlias: 0 -> VMware VMXNET3 Ethernet Controller
2017-01-15 22:35:10	debian86_vm	eth0	ifDescr: 0 -> VMware VMXNET3 Ethernet Controller
2017-01-15 22:35:10	debian86_vm	lo	ifConnectorPresent: 0 -> false
2017-01-15 22:35:10	debian86_vm	lo	ifPromiscuousMode: 0 -> false
2017-01-15 22:35:10	debian86_vm	lo	ifType: 0 -> softwareLoopback
2017-01-15 22:35:10	debian86_vm	lo	ifOperStatus: 0 -> up
2017-01-15 22:35:10	debian86_vm	lo	ifAdminStatus: 0 -> up
2017-01-15 22:35:10	debian86_vm	lo	ifAlias: 0 -> lo
2017-01-15 22:35:10	debian86_vm	lo	ifDescr: 0 -> lo
2017-01-15 22:34:02	localhost	NULL	Could not issue critical alert for rule 'Sensor under limit' to transport 'mail' Error: You must provide at least one recipient email address.
2017-01-15 22:30:09	debian86_vm	eth0	ifDuplex: 0 -> fullDuplex
2017-01-15 22:30:09	debian86_vm	eth0	ifConnectorPresent: 0 -> true
2017-01-15 22:30:09	debian86_vm	eth0	ifPromiscuousMode: 0 -> false
2017-01-15 22:30:09	debian86_vm	eth0	ifPhysAddress: 0 -> 005056bf4050
2017-01-15 22:30:09	debian86_vm	eth0	ifType: 0 -> ethernetCsmacd
2017-01-15 22:30:09	debian86_vm	eth0	ifOperStatus: 0 -> up
2017-01-15 22:30:09	debian86_vm	eth0	ifAdminStatus: 0 -> up
2017-01-15 22:30:09	debian86_vm	eth0	ifAlias: 0 -> VMware VMXNET3 Ethernet Controller
2017-01-15 22:30:09	debian86_vm	eth0	ifDescr: 0 -> VMware VMXNET3 Ethernet Controller
2017-01-15 22:30:09	debian86_vm	lo	ifConnectorPresent: 0 -> false
2017-01-15 22:30:09	debian86_vm	lo	ifPromiscuousMode: 0 -> false
2017-01-15 22:30:09	debian86_vm	lo	ifType: 0 -> softwareLoopback
2017-01-15 22:30:09	debian86_vm	lo	ifOperStatus: 0 -> up
2017-01-15 22:30:09	debian86_vm	lo	ifAdminStatus: 0 -> up
2017-01-15 22:30:09	debian86_vm	lo	ifAlias: 0 -> lo
2017-01-15 22:30:09	debian86_vm	lo	ifDescr: 0 -> lo
2017-01-15 22:29:01	localhost	NULL	Could not issue critical alert for rule 'Sensor under limit' to transport 'mail' Error: You must provide at least one recipient email address.
2017-01-15 22:25:09	debian86_vm	eth0	ifDuplex: 0 -> fullDuplex
2017-01-15 22:25:09	debian86_vm	eth0	ifConnectorPresent: 0 -> true
2017-01-15 22:25:09	debian86_vm	eth0	ifPromiscuousMode: 0 -> false
2017-01-15 22:25:09	debian86_vm	eth0	ifPhysAddress: 0 -> 005056bf4050
2017-01-15 22:25:09	debian86_vm	eth0	ifType: 0 -> ethernetCsmacd
2017-01-15 22:25:09	debian86_vm	eth0	ifOperStatus: 0 -> up
2017-01-15 22:25:09	debian86_vm	eth0	ifAdminStatus: 0 -> up
2017-01-15 22:25:09	debian86_vm	eth0	ifAlias: 0 -> VMware VMXNET3 Ethernet Controller
2017-01-15 22:25:09	debian86_vm	eth0	ifDescr: 0 -> VMware VMXNET3 Ethernet Controller
2017-01-15 22:25:09	debian86_vm	lo	ifConnectorPresent: 0 -> false
2017-01-15 22:25:09	debian86_vm	lo	ifPromiscuousMode: 0 -> false
2017-01-15 22:25:09	debian86_vm	lo	ifType: 0 -> softwareLoopback

snmpd (NET-SNMP version:  5.7.2.1) is correctly returning data

> #### Load disco module ports #### SNMP[/usr/bin/snmpbulkwalk -v3 -n '' -l 'authPriv' -a 'SHA' -A 'auth' -u 'nms' -x 'AES' -X 'priv' -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro
> udp:HOSTNAME:161 ifDescr] ifDescr.1 = lo ifDescr.2 = VMware VMXNET3
> Ethernet Controller
> 
> SNMP[/usr/bin/snmpbulkwalk -v3 -n '' -l 'authPriv' -a 'SHA' -A 'auth'
> -u 'nms' -x 'AES' -X 'priv' -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro udp:HOSTNAME:161
> ifName] ifName.1 = lo ifName.2 = eth0
> 
> SNMP[/usr/bin/snmpbulkwalk -v3 -n '' -l 'authPriv' -a 'SHA' -A 'auth'
> -u 'nms' -x 'AES' -X 'priv' -OQUs -m IF-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro udp:HOSTNAME:161
> ifType] ifType.1 = softwareLoopback ifType.2 = ethernetCsmacd
> 
> Array (
>     [1] => Array
>         (
>             [ifDescr] => lo
>             [ifName] => lo
>             [ifType] => softwareLoopback
>         )
> 
>     [2] => Array
>         (
>             [ifDescr] => VMware VMXNET3 Ethernet Controller
>             [ifName] => eth0
>             [ifType] => ethernetCsmacd
>         )
> 
> ) SQL[SELECT `name` FROM `port_association_mode` WHERE pom_id = '1'] 
> SQL[SELECT * FROM `ports` WHERE `device_id` = '12' ORDER BY port_id] 
> ..
> 
>  Runtime for discovery module 'ports': 0.1300 seconds

**Comment by laf** [comment]
Update, this was fixed earlier.

**Comment by jkldgoefgkljefogeg** [comment]
Can you kindly point out which commit fixed it?

**Comment by laf** [comment]
https://github.com/librenms/librenms/pull/5442/commits/b8d70f900a67bdeeef7a71043412563e06b3029f

**Comment by jkldgoefgkljefogeg** [comment]
I am still seeing similar events, now about CPU. SNMP poller on ESXi 6.5

> 2017-01-20 06:34:27	esxi65	processor	Processor added: type hr index 24
> descr 0/23/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 23 descr
> 0/22/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 22 descr
> 0/21/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 21 descr
> 0/20/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 20 descr
> 0/19/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 19 descr
> 0/18/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 18 descr
> 0/17/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 17 descr
> 0/16/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 16 descr
> 0/15/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 15 descr
> 0/14/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 14 descr
> 0/13/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 13 descr
> 0/12/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 12 descr
> 0/11/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 06:34:27	esxi65	processor	Processor added: type hr index 11 descr
> 0/10/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 24 descr
> 0/23/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 23 descr
> 0/22/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 22 descr
> 0/21/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 21 descr
> 0/20/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 20 descr
> 0/19/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 19 descr
> 0/18/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 18 descr
> 0/17/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 17 descr
> 0/16/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 16 descr
> 0/15/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 15 descr
> 0/14/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 14 descr
> 0/13/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 13 descr
> 0/12/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 12 descr
> 0/11/0 Genuine Intel 0000 @ 1.80GHz 2017-01-20
> 00:34:19	esxi65	processor	Processor removed: type hr index 11 descr
> 0/10/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	mempool	Memory pool added: type hrstorage index 6
> descr Real Memory 2017-01-18 12:34:36	esxi65	processor	Processor
> added: type hr index 24 descr 0/23/0 Genuine Intel 0000 @ 1.80GHz
> 2017-01-18 12:34:36	esxi65	processor	Processor added: type hr index 23
> descr 0/22/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 22 descr
> 0/21/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 21 descr
> 0/20/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 20 descr
> 0/19/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 19 descr
> 0/18/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 18 descr
> 0/17/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 17 descr
> 0/16/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 16 descr
> 0/15/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 15 descr
> 0/14/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 14 descr
> 0/13/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 13 descr
> 0/12/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 12 descr
> 0/11/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 12:34:36	esxi65	processor	Processor added: type hr index 11 descr
> 0/10/0 Genuine Intel 0000 @ 1.80GHz 2017-01-18
> 06:34:36	esxi65	mempool	Memory pool added: type hrstorage index 1
> descr Real Memory 2017-01-18 06:34:36	esxi65	processor	Processor
> removed: type hr index 24 descr 0/23/0 Genuine Intel 0000 @ 1.80GHz
> 2017-01-18 06:34:36	esxi65	processor	Processor removed: type hr index
> 23 descr 0/22/0 Genuine Intel 0000 @ 1.80GHz

**Comment by laf** [comment]
I don't think this is related. Vmware is known for its poor snmp implementation so it could be that. Either way create a new issue and provide the info we ask for
