### ISSUE TITLE
QNAP snmp readings broken since #5925

### ISSUE THREAD

**Issue by tuxi56** [librenms/librenms#5946]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Component | Version
--------- | -------
LibreNMS  | bf7656923e951d8b596e6be8cc232d9fb5a43845
DB Schema | 165
PHP       | 7.0.16-1~dotdeb+8.1
MySQL     | 5.5.54-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1

Hi

I have no readings from my two QNAP NAS (TS-112P and TS-259 Pro+) in LibreNMS (no bandwith, no cpu usage, no memory, no storage, nothing) since 2017-02-18 shortly after the daily.sh, all I could find by this period of time was the #5925 pr. 

Event log for Turbo NAS TS-259 Pro+ : 
![image](https://cloud.githubusercontent.com/assets/22138991/23103278/26762ca8-f6b9-11e6-9c84-7b76fdb3b080.png)

Event log for Turbo NAS TS-112P : 
![image](https://cloud.githubusercontent.com/assets/22138991/23103510/60609518-f6bc-11e6-93be-2b8bc7150edf.png)

I'm unable to provide you discovery.php or poller.php logs for those devices, because of `Timeout: No Response from udp:<IP_ADDRESS>:161.` It seems that the snmp process on the NAS crashes when the poller runs (when manually restarting, all I can do is snmpbulkwalk ; if I run poller.php just after it hangs with timeout message). 

EDIT - here's what I was able to extract from those devices (nothing fancy) : 

Turbo NAS TS-259 Pro+ : 
- discovery + poller : http://pastebin.com/iF2xtXsE
- snmpblukwalk : http://pastebin.com/SuCT6FH4

Turbo NAS TS-112P : 
- discovery + poller : http://pastebin.com/Kj4gdngL
- snmpblukwalk : http://pastebin.com/vzTLai9X

Even a periodic (cron) restart of snmp doesn't solve the issue. Ping is ok for both devices from the NMS (smokeping). 

Any idea what could happen ? 

Thanks

**Comment by laf** [comment]
This is because both of these devices don't have a sysObjectId which we use for detecting if a device is up or down. Previously we didn't do this check in discovery but now we do, however that still shouldn't make a difference as poller would not run anyway.

If I'm honest, Qnap should fix this. Not returning a sysObjectId is just fundamentally wrong of them. Maybe it's a firmware issue?

We could switch our snmp check to just see if udp 161 is responding instead but I'm not sure if that will give us any false positives.

**Comment by tuxi56** [comment]
So now because of no sysObjectId the poller get rid of the device and checks for the next device ? The fact is that previously the poller did read some data from both devices (right cpu info, etc). 

I can't read anything related to snmp from the QNAP firmware changelog, so no pledge of resolution by this way. 

Here's the MIB (identical for both devices) but I think you already have it : http://pastebin.com/47wZcFNJ

I think I have a similar behaviour on another device (FreeNAS 10) : previously I get data from everything (CPU, memory, storage) and suddenly no storage usage information. No other updates than LibreNMS auto-update.

**Comment by laf** [comment]
I might have a solution but the short of this is it's a QNAP issue and not ours, they should fix this rather than the expectation that we will work round it.

**Comment by tuxi56** [comment]
I forgot the `.` at the end of the `snmpbulkwalk` command for the Turbo NAS TS-259 Pro+, seems more consequent, here's the output : http://pastebin.com/FGuunqeX. 

Reference to sysObjectId at line 1955, would it help ?

**Comment by laf** [comment]
sysObjectId is .1.3.6.1.2.1.1.2.0 which doesn't exist in your output.

**Comment by tuxi56** [comment]
Ok no sysObjectId, that's a shame. According to https://forum.qnap.com/viewtopic.php?t=86641 this issue lasts from 2013 at least, and not solved by 2017. My guess is that it will never be. 

Doesn't the given MIB matches the snmpwalks (I'm not a snmp specialist) ? 

How could we make it work again ?

**Comment by laf** [comment]
Please try this patch:

```
diff --git a/includes/functions.php b/includes/functions.php
index fd89494..da82018 100644
--- a/includes/functions.php
+++ b/includes/functions.php
@@ -557,15 +557,16 @@ function isSNMPable($device)
 {
     global $config;

-    $pos = snmp_get($device, "sysObjectID.0", "-Oqv", "SNMPv2-MIB");
-    if (empty($pos)) {
-        // Support for Hikvision
-        $pos = snmp_get($device, "SNMPv2-SMI::enterprises.39165.1.1.0", "-Oqv", "SNMPv2-MIB");
-    }
-    if ($pos === '' || $pos === false) {
-        return false;
-    } else {
+    $pos = snmp_check($device);
+    if ($pos === true) {
         return true;
+    } else {
+        $pos = snmp_get($device, "sysObjectID.0", "-Oqv", "SNMPv2-MIB");
+        if ($pos === '' || $pos === false) {
+            return false;
+        } else {
+            return true;
+        }
     }
 }

diff --git a/includes/snmp.inc.php b/includes/snmp.inc.php
index fb964f0..c4241b8 100644
--- a/includes/snmp.inc.php
+++ b/includes/snmp.inc.php
@@ -255,6 +255,25 @@ function snmp_get($device, $oid, $options = null, $mib = null, $mibdir = null)
     }
 }//end snmp_get()

+/**
+ * @param $device
+ * @return bool
+ */
+function snmp_check($device)
+{
+    $time_start = microtime(true);
+
+    $oid = '.1.3.6.1.2.1.1.2.0';
+    $options = '-Oqvn';
+
+    $cmd = gen_snmpget_cmd($device, $oid, $options);
+    exec($cmd, $data, $code);
+    d_echo("SNMP Check response code: $code".PHP_EOL);
+    if ($code === 0) {
+        return true;
+    }
+    return false;
+}//end snmp_check()

 function snmp_walk($device, $oid, $options = null, $mib = null, $mibdir = null)
 {

```

**Comment by tuxi56** [comment]
Patch applied, waiting for next polling (waiting for 15 min?)

**Comment by laf** [comment]
5 mins should be fine to have it now show up as down, but for data yes about 15 mins

**Comment by NK74** [comment]
Hi @laf 

I have same issue on a QNAP on my prod

**Comment by laf** [comment]
Try the same patch then

**Comment by NK74** [comment]
Ok for me

**Comment by laf** [comment]
As in it works?

**Comment by NK74** [comment]
I did not say, i have not used your patch ;s

re-run full discovery and wait 15min

**Comment by tuxi56** [comment]
Nothing new for me, my two QNAP devices are still unavailable (no readings from cpu memory etc). 

![image](https://cloud.githubusercontent.com/assets/22138991/23108027/de2bb9ec-f706-11e6-97b1-85ee654b9c5d.png)

**Comment by laf** [comment]
Need the output of `./poller.php -h HOSTNAME -d -m os`

**Comment by tuxi56** [comment]
Here : http://pastebin.com/xGr32Ptf

**Comment by laf** [comment]
You're getting timeouts on actual snmp:

Timeout: No Response from udp:10.44.30.10:161.

We can't do anything about that, the patch itself has worked as expected and detected the error.

**Comment by tuxi56** [comment]
Ok I restarted the snmp process on the NAS, here's the output : http://pastebin.com/jUMQTdHN. 

Fingers crossed for the process not to crash.

**Comment by laf** [comment]
That shows the poller ran ok again. If after that you get a timeout then you really need to raise this with qnap

**Comment by tuxi56** [comment]
I updated my Turbo NAS TS-259 Pro+ to the latest firmware version : no further success. 

According to https://forum.qnap.com/viewtopic.php?f=50&t=31773&start=15#p409472 it's possible to tune the DoS detection (or disable it) (because I get the [SNMP] DoS detected message depicted in https://community.librenms.org/t/librenms-qnap-snmp-dos-detected/363). Same thing : first poller runs well, the next won't even with disabling DoS detection. 

Strange behaviour : I disabled the device polling in LibreNMS for both device, and I was able to run snmpwalk's multiple times from my PC (I even run the command multiple times at once from different terminals) -> no crash of the snmp daemon server side. 

When re-enabling device polling in LibreNMS and running poller.php manually -> immediate crask of snmp daemon with classical `Timeout: No Response from udp:10.44.30.10:161`. 

This makes me definitely think the problem is in the NMS poller code. But a git checkout to an older revision (last week) didn't solved the issue.

**Comment by laf** [comment]
The issue is with the qnap device and how it's handling the snmp queries - it is most likely not able to sustain how hard we hit the unit.

Doing a bulkwalk isn't any indication of it being a code issue, a walk doesn't do the requests we do and is basically just doing a bulk getnext so asking for data one by one.

You should tune down the numbers for so it produces a lower number of requests - I'm not sure this will help but it's worth a shot.

http://docs.librenms.org/Support/Performance/#snmp-max-repeaters

http://docs.librenms.org/Support/Performance/#snmp-max-oids

**Comment by laf** [comment]
Also the link you showed has the option to change the MaxPacketPerSecond for the qnap unit, I expect you should also tweak that.

**Comment by tuxi56** [comment]
Hi @laf 

> it is most likely not able to sustain how hard we hit the unit

This isn't reassuring :)

On my yesterday tests I did tune the `MaxPacketPerSecond` with values up to 2147483647 while keeping `EnableDetectDDoS` to true, with no success : every time I run the poller, the snmp process crashes. Fun fact : while poller.php is running (hanging between modules) I tried to restart the snmp process : the poller gets some extra data (quick output in the webGUI in Capture), and then hangs again, untin I restart snmp, etc. 

Even with `EnableDetectDDoS` to false, the issue remains the same (no effect ?)

Here's the poller output I was able to extract by this morning : http://pastebin.com/SyV6S5vW

Please forgive if I feel like annoying with this, I simply don't understand why something working well for months suddenly doesn't, just a few seconds after an update, with no other modifications than the NMS code. Plus the fact that my 2 QNAP devices were unpollable at the same time. Am I the only one with QNAP devices ? @NK74 what's new with your setup ? 

What values should you recommend for max-repeaters and max-oids ? 

My approach with snmpbulkwalk was to narrow the fact that the snmp server is available for requests or not, from another PC. 

Should I keep your patch or revert to master version ? 

Regards,

**Comment by laf** [comment]
That poller output doesn't show it having timed out so from that alone it doesn't look like it's our code causing it to crash. Does it timeout regularly or when discovery runs for the device?

Values for max repeaters and max oids can't be given, you'll have to test lowering them until either snmp doesn't crash or poll times are too long. However I'm less confident that this will help as you can do a full poll successfully.

You could try going back to older commits until you find a working version and we can see what's different.

I can't really do much else without snmp and ssh access to a unit to do some actual debugging.

**Comment by tuxi56** [comment]
Yes the poller makes regular timeouts (when running manually via Capture). 

Ok here's some extra info from the QNAP kmesg right ahead of a poller run : 

`snmpd[6535]: segfault at 0 ip b75ff371 sp bfb39570 error 4 in libnetsnmpmibs.so.20.0.0[b75d6000+116000]`

Does it means that the poller tries to query a value (from the MIB) that is out of the limits, makes the snmp server segfault? 

I tried to rollback to friday's afternoon commit https://github.com/librenms/librenms/commit/c6f6cf1f091f51aef1376abe1a29b126f09dcad1 but it didn't work better. 

I think I will try to make a fresh distinct LibreNMS install with this device only, we'll see if it's better and it will allow to rollback to any older commit.

**Comment by laf** [comment]
If this literally started from one update to another then you can look in logs/daily.log to see what commit it went from and to.

**Comment by tuxi56** [comment]
FYI the segfault occurs here at the end of this poller output : http://pastebin.com/3dkDf4Hi 

After that regular poller timeout happen.

**Comment by laf** [comment]
Run that query manually and see if you can reproduce:

/usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.2.15.1.3.3.6.1.4.1.1 .1.3.6.1.4.1.24681.1.2.15.1.3.1

Replace the obvious in the above.

**Comment by laf** [comment]
Actually those oids are the old ones from before the fixes. You could just delete all sensors from that device: DELETE FROM `sensors` WHERE `device_id`=X;

**Comment by tuxi56** [comment]
Checkout to 24aaf17 (2 updates earlier at 2017-02-16) doesn't work better :(

> /usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.2.15.1.3.3.6.1.4.1.1 .1.3.6.1.4.1.24681.1.2.15.1.3.1

segfault server side, `Timeout: No Response from udp:10.44.30.10:161.` NMS side.

**Comment by laf** [comment]
Run that delete command.

**Comment by tuxi56** [comment]
done before and after, same result.

**Comment by laf** [comment]
But the query shouldn't be the same now, post the poller output

**Comment by tuxi56** [comment]
New discovery : http://pastebin.com/q3iqSSaA

```
mysql> select sensor_id, sensor_class, device_id, sensor_oid, sensor_type, sensor_descr from sensors where device_id = 21;
+-----------+--------------+-----------+---------------------------------+-------------------+------------------------+
| sensor_id | sensor_class | device_id | sensor_oid                      | sensor_type       | sensor_descr           |
+-----------+--------------+-----------+---------------------------------+-------------------+------------------------+
|        91 | fanspeed     |        21 | .1.3.6.1.4.1.24681.1.2.15.1.3.1 | snmp              | System FAN 1           |
|        92 | state        |        21 | .1.3.6.1.4.1.24681.1.2.11.1.4.1 | qnap_hdd_status_1 | HDD 1 status           |
|        93 | state        |        21 | .1.3.6.1.4.1.24681.1.2.11.1.4.2 | qnap_hdd_status_2 | HDD 2 status           |
|        94 | temperature  |        21 | .1.3.6.1.4.1.24681.1.3.6.0      | snmp              | System Temperature     |
|        95 | temperature  |        21 | .1.3.6.1.4.1.24681.1.2.11.1.3.1 | snmp              | HDD 1 WD2003FYYS-02W0B |
|        96 | temperature  |        21 | .1.3.6.1.4.1.24681.1.2.11.1.3.2 | snmp              | HDD 2 WD2003FYYS-02W0B |
+-----------+--------------+-----------+---------------------------------+-------------------+------------------------+
```

```
$ /usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.2.15.1.3.1
.1.3.6.1.4.1.24681.1.2.15.1.3.1 = "1753 RPM"

$ /usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.2.11.1.4.1
.1.3.6.1.4.1.24681.1.2.11.1.4.1 = 0

$ /usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.3.6.0
.1.3.6.1.4.1.24681.1.3.6.0 = 41

$ /usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.2.11.1.3.1
.1.3.6.1.4.1.24681.1.2.11.1.3.1 = "41 C/105 F"
```

**Comment by tuxi56** [comment]
So now the poller run twice (first time manually, second by the cron) and no segfault on the QNAP, device polled ok, no data in rrdgraphs (delayed?) ; here's the first output : http://pastebin.com/1CfkPeZS

![image](https://cloud.githubusercontent.com/assets/22138991/23164583/1f680898-f838-11e6-9f48-ac7eda0c9cc7.png)

The only difference I see is the deletion of sensors in the database. Right? 

(must be my lunch)

**Comment by tuxi56** [comment]
So does the second device TS-112P (we were working on TS-259 Pro+) : deletion of sensors in database -> discovery -> poller -> ok :)

**Comment by laf** [comment]
So the qnap is bombing out due to oid's being looked up that don't exist, you really should raise that to them as that shouldn't happen.

**Comment by tuxi56** [comment]
I agree this is a crappy behaviour... 

Sorry for blaming the code ; wouldn't a discovery (with an up and running snmp server) have replaced the "old" oid's in the database? 

Next test : remove the patch you provided earlier.

**Comment by tuxi56** [comment]
Patch removed, no noticeable effect. 

Thank you @laf
